# serverless.yml
service: my-restful-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  environment:
    DYNAMODB_TABLE: FusionadosData
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:us-east-1:123456789012:table/FusionadosData"

functions:
  fusionados:
    handler: handler.fusionados
    events:
      - http:
          path: fusionados
          method: get
  almacenar:
    handler: handler.almacenar
    events:
      - http:
          path: almacenar
          method: post
  historial:
    handler: handler.historial
    events:
      - http:
          path: historial
          method: get

resources:
  Resources:
    FusionadosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FusionadosData
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST


# Agregar plugins
plugins:
  - serverless-offline
  - serverless-dynamodb-local

# Configurar Serverless Offline
custom:
  serverless-offline:
    httpPort: 3000  # Cambia el puerto si es necesario
    lambdaPort: 3002
    host: 0.0.0.0  # Escucha en todas las interfaces de red
