# serverless.yml
service: my-restful-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  getUsers:
    handler: handler.getUsers
    events:
      - http:
          path: users
          method: get
  createUser:
    handler: handler.createUser
    events:
      - http:
          path: users
          method: post
  getUser:
    handler: handler.getUser
    events:
      - http:
          path: users/{id}
          method: get
  updateUser:
    handler: handler.updateUser
    events:
      - http:
          path: users/{id}
          method: put
  deleteUser:
    handler: handler.deleteUser
    events:
      - http:
          path: users/{id}
          method: delete
