# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: hache
service: my-restful-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-west-2
  environment:
    DYNAMODB_TABLE: FusionadosData
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:us-west-2:123456789012:table/FusionadosData" # Corregida la región

functions:
  fusionados:
    handler: dist/handler.fusionados  # Asegúrate de que tu código está en src/
    events:
      - http:
          path: fusionados
          method: get
  almacenar:
    handler: dist/handler.almacenar
    events:
      - http:
          path: almacenar
          method: post
  historial:
    handler: dist/handler.historial
    events:
      - http:
          path: historial
          method: get

resources:
  Resources:
    FusionadosTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: FusionadosData
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

# Agregar plugins
plugins:
  - serverless-offline
  - serverless-dynamodb-local

# Configurar Serverless Offline y ESBuild
custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3002
    host: 0.0.0.0
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node20
    platform: node
    concurrency: 10
